//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioCALC.Locale {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scores() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioCALC.Locale.Scores", typeof(Scores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amylose cardiaque.
        /// </summary>
        internal static string Amyloidosis {
            get {
                return ResourceManager.GetString("Amyloidosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probabilité d&apos;amylose cardiaque en cas d&apos;hypertrophie ventriculaire.
        /// </summary>
        internal static string Amyloidosis_Detail {
            get {
                return ResourceManager.GetString("Amyloidosis_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMC &amp; Poids idéal.
        /// </summary>
        internal static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calcul de l&apos;IMC et du poids idéal pour la taille.
        /// </summary>
        internal static string BMI_Detail {
            get {
                return ResourceManager.GetString("BMI_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formule de Devine pour les hommes..
        /// </summary>
        internal static string BMI_IdealWeightManFormulaName {
            get {
                return ResourceManager.GetString("BMI_IdealWeightManFormulaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gentamicin therapy. Devine, BJ. Drug Intell Clin Pharm, 1974;8:650–5..
        /// </summary>
        internal static string BMI_IdealWeightManSource {
            get {
                return ResourceManager.GetString("BMI_IdealWeightManSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://scholar.google.com/scholar_lookup?hl=en&amp;publication_year=1974&amp;pages=650-5&amp;author=BJ+Devine&amp;title=Gentamicin+therapy.
        /// </summary>
        internal static string BMI_IdealWeightManURL {
            get {
                return ResourceManager.GetString("BMI_IdealWeightManURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formule de Robinson pour les femmes..
        /// </summary>
        internal static string BMI_IdealWeightWomanFormulaName {
            get {
                return ResourceManager.GetString("BMI_IdealWeightWomanFormulaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Determination of ideal body weight for drug dosage calculations. Robinson JD, et al. Am J Hosp Pharmacology, 1983;40(6):1016-9..
        /// </summary>
        internal static string BMI_IdealWeightWomanSource {
            get {
                return ResourceManager.GetString("BMI_IdealWeightWomanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://www.researchgate.net/deref/http%3A%2F%2Fwww.ingentaselect.com%2Frpsv%2Fcgi-bin%2Flinker%3Fext%3Da%26reqidx%3D0002-9289%281983%2940L.1016%5Baid%3D6802988%5D.
        /// </summary>
        internal static string BMI_IdealWeightWomanURL {
            get {
                return ResourceManager.GetString("BMI_IdealWeightWomanURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMC normal.
        /// </summary>
        internal static string BMI_Interpretation_Normal {
            get {
                return ResourceManager.GetString("BMI_Interpretation_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obésité modérée (grade 1).
        /// </summary>
        internal static string BMI_Interpretation_Obesity1 {
            get {
                return ResourceManager.GetString("BMI_Interpretation_Obesity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obésité sévère (grade 2).
        /// </summary>
        internal static string BMI_Interpretation_Obesity2 {
            get {
                return ResourceManager.GetString("BMI_Interpretation_Obesity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obésité mordide (grade 3).
        /// </summary>
        internal static string BMI_Interpretation_Obesity3 {
            get {
                return ResourceManager.GetString("BMI_Interpretation_Obesity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surpoids.
        /// </summary>
        internal static string BMI_Interpretation_Overweight {
            get {
                return ResourceManager.GetString("BMI_Interpretation_Overweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maigreur extrême.
        /// </summary>
        internal static string BMI_Interpretation_SevereThinness {
            get {
                return ResourceManager.GetString("BMI_Interpretation_SevereThinness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maigreur.
        /// </summary>
        internal static string BMI_Interpretation_Thinness {
            get {
                return ResourceManager.GetString("BMI_Interpretation_Thinness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classification de l&apos;IMC selon l&apos;Organisation Mondiale de la Santé..
        /// </summary>
        internal static string BMI_Source {
            get {
                return ResourceManager.GetString("BMI_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMC &amp; Poids idéal.
        /// </summary>
        internal static string BMI_TitleName {
            get {
                return ResourceManager.GetString("BMI_TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://apps.who.int/bmi/index.jsp?introPage=intro_3.html.
        /// </summary>
        internal static string BMI_URL {
            get {
                return ResourceManager.GetString("BMI_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calculs.
        /// </summary>
        internal static string Calculations {
            get {
                return ResourceManager.GetString("Calculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canadian Syncope Risk.
        /// </summary>
        internal static string CanadianSyncopeRisk {
            get {
                return ResourceManager.GetString("CanadianSyncopeRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Risque d&apos;évènement cardiovasculaire après syncope.
        /// </summary>
        internal static string CanadianSyncopeRisk_Detail {
            get {
                return ResourceManager.GetString("CanadianSyncopeRisk_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clairance de la créatinine.
        /// </summary>
        internal static string Clearance {
            get {
                return ResourceManager.GetString("Clearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation de la fonction rénale.
        /// </summary>
        internal static string Clearance_Detail {
            get {
                return ResourceManager.GetString("Clearance_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insuffisance cardiaque.
        /// </summary>
        internal static string HeartFailure {
            get {
                return ResourceManager.GetString("HeartFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PH-HFpEF Group.
        /// </summary>
        internal static string PhhfGroup {
            get {
                return ResourceManager.GetString("PhhfGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les stratégies de prise en charge proposées ici sont tirées du [calculateur en ligne sur le site du GICC](https://giccardio.fr/medecin/outils/calcul-de-scores/) (Groupe Insuffisance Cardiaque et Cardiomyopathies de la Société Française de Cardiologie) et n&apos;ont pas fait l&apos;objet d&apos;une validation prospective..
        /// </summary>
        internal static string PhhfGroup_Advert {
            get {
                return ResourceManager.GetString("PhhfGroup_Advert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classification non-invasive des hypertensions pulmonaires avec FEVG préservée (&gt; 50 %). Un score &gt; 6 a une spécificité &gt; 95% pour une hypertension pulmonaire post-capillaire du groupe 2 (insuffisance cardiaque gauche)..
        /// </summary>
        internal static string PhhfGroup_Description {
            get {
                return ResourceManager.GetString("PhhfGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classification de l&apos;hypertension pulmonaire.
        /// </summary>
        internal static string PhhfGroup_Detail {
            get {
                return ResourceManager.GetString("PhhfGroup_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référer le patient à un centre de référence d&apos;hypertension pulmonaire pour cathétérisme cardiaque droit..
        /// </summary>
        internal static string PhhfGroup_Interpretation_Intermediate {
            get {
                return ResourceManager.GetString("PhhfGroup_Interpretation_Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forte probabilité d&apos;hypertension pulmonaire post-capillaire dans le cadre d&apos;une insuffisance cardiaque : traiter le patient avec des diurétiques et réévaluer..
        /// </summary>
        internal static string PhhfGroup_Interpretation_Postcapillary {
            get {
                return ResourceManager.GetString("PhhfGroup_Interpretation_Postcapillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forte probabilité d&apos;hypertension pulmonaire pré-capillaire : référer le patient à un centre de référence d&apos;HTP pour cathétérisme cardiaque droit..
        /// </summary>
        internal static string PhhfGroup_Interpretation_Precapillary {
            get {
                return ResourceManager.GetString("PhhfGroup_Interpretation_Precapillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Clinical and Echocardiographic Score to Identify Pulmonary Hypertension Due to HFpEF. Berthelot E, et al. Journal of Cardiac Failure, 2017;23(1):29-35..
        /// </summary>
        internal static string PhhfGroup_Source {
            get {
                return ResourceManager.GetString("PhhfGroup_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score PH-HFpEF Group.
        /// </summary>
        internal static string PhhfGroup_TitleName {
            get {
                return ResourceManager.GetString("PhhfGroup_TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://dx.doi.org/10.1016/j.cardfail.2016.10.002.
        /// </summary>
        internal static string PhhfGroup_URL {
            get {
                return ResourceManager.GetString("PhhfGroup_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rythmologie.
        /// </summary>
        internal static string Rhythmology {
            get {
                return ResourceManager.GetString("Rhythmology", resourceCulture);
            }
        }
    }
}
